name = "fabulous"
version = "1.0.0"

description = "A simple gleam library for creating tables based on columns and rows."
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
